language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # Tags
  - docker tag udagram-api-feed omairmuhi/udagram-api-feed:v12
  - docker tag udagram-api-user omairmuhi/udagram-api-user:v9
  - docker tag udagram-frontend omairmuhi/udagram-frontend:v14
  - docker tag udagram-reverseproxy omairmuhi/udagram-reverseproxy:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push omairmuhi/udagram-api-feed:v12
  - docker push omairmuhi/udagram-api-user:v9
  - docker push omairmuhi/udagram-frontend:v14
  - docker push omairmuhi/udagram-reverseproxy:v1
# kubectl apply -f deployment/backend-user-deployment.yaml && kubectl apply -f service/backend-user-service.yaml

