apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: omairmuhi/udagram-api-feed:v12
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: JWT_SECRET
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_PROFILE
        - name: AWS_REGION 
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_REGION
        - name: AWS_BUCKET 
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: AWS_BUCKET 
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-configmap
              key: POSTGRES_HOST
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: psql-db-pass
              key: postgres_username.txt
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql-db-pass
              key: postgres_pass.txt
        - name: AWS_ACCESS_KEY_ID 
          valueFrom:
            secretKeyRef:
              name: aws-pass
              key: aws_username.txt 
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-pass
              key: aws_pass.txt 
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
